// Generated by CoffeeScript 1.6.3
var count, end, start, _, _i;

start = Date.now();

count = 10 * 1000;

for (_ = _i = 0; 0 <= count ? _i <= count : _i >= count; _ = 0 <= count ? ++_i : --_i) {
  outputBuffers.length = 0;
  main();
  HDF.call(Dataset, json);
  outputBuffers.join("");
}

end = Date.now();

console.log(end - start, "ms");

console.log(count, "task ,", (end - start) / count, "per task");

console.log("result", outputBuffers.join(""));
